name: No Response

on:
  schedule:
    - cron: "0 12 * * *" # Runs daily at noon
  workflow_dispatch:

jobs:
  call-no-response-workflow:
    uses: FossifyOrg/.github/.github/workflows/no-response.yml@main
    with:
      app-id: ${{ secrets.APP_ID }}
      private-key: ${{ secrets.APP_PRIVATE_KEY }}
