name: Prepare Release PR

on:
  workflow_dispatch:
    inputs:
      based_on:
        description: "Base branch or tag to base the release on"
        required: true
        type: string
      feature_branch:
        description: "Branch containing additional features"
        default: "feature/_main-message-mirror"
        type: string

jobs:
  prepare-release-branch:
    name: Prepare release branch from VERSION_NAME
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ensure full history for rebase operations

      - name: Show repository files (debug)
        run: |
          echo "Listing repository root files for debug"
          ls -la

      - name: Create release branch
        run: |
          git fetch upstream --tags

          git checkout ${{inputs.feature_branch}}
          git checkout -b __test
          git rebase --onto ${{inputs.based_on}} origin/main __test
          git push origin __test
