name: Fastlane metadata validation

on:
  push:
    branches: [main, feature/_main-message-mirror]
    paths:
      - "fastlane/**"
  pull_request:
    branches: [main, feature/_main-message-mirror]
    paths:
      - "fastlane/**"

jobs:
  validate:
    uses: FossifyOrg/.github/.github/workflows/validate-fastlane-metadata.yml@main
